/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentPartial = IDL.Record({
  'id' : IDL.Text,
  'tokenNumber' : IDL.Nat,
});
export const PatientRecord = IDL.Record({
  'id' : IDL.Text,
  'doctorNotes' : IDL.Text,
  'prescription' : IDL.Text,
  'patientId' : IDL.Text,
  'visitDate' : IDL.Text,
  'diagnosis' : IDL.Text,
  'patientName' : IDL.Text,
  'doctorName' : IDL.Text,
  'department' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'appointmentCount' : IDL.Nat,
  'doctorCount' : IDL.Nat,
  'patientCount' : IDL.Nat,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'tokenNumber' : IDL.Nat,
  'patientId' : IDL.Text,
  'createdAt' : IDL.Int,
  'appointmentDate' : IDL.Text,
  'patientName' : IDL.Text,
  'doctorName' : IDL.Text,
  'department' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const LoginResponse = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'sessionToken' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AppointmentPartial, 'err' : IDL.Text })],
      [],
    ),
  'completeConsultation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'confirmPayment' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'getAllConsultations' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(PatientRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyAppointments' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Appointment), 'err' : IDL.Text })],
      ['query'],
    ),
  'getPatientRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(PatientRecord), 'err' : IDL.Text })],
      ['query'],
    ),
  'getQueue' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(Appointment), 'err' : IDL.Text })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : LoginResponse, 'err' : IDL.Text })],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'resetAppointments' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'userId' : IDL.Text,
            'name' : IDL.Text,
            'role' : IDL.Text,
          })
        ),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentPartial = IDL.Record({
    'id' : IDL.Text,
    'tokenNumber' : IDL.Nat,
  });
  const PatientRecord = IDL.Record({
    'id' : IDL.Text,
    'doctorNotes' : IDL.Text,
    'prescription' : IDL.Text,
    'patientId' : IDL.Text,
    'visitDate' : IDL.Text,
    'diagnosis' : IDL.Text,
    'patientName' : IDL.Text,
    'doctorName' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'appointmentCount' : IDL.Nat,
    'doctorCount' : IDL.Nat,
    'patientCount' : IDL.Nat,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'tokenNumber' : IDL.Nat,
    'patientId' : IDL.Text,
    'createdAt' : IDL.Int,
    'appointmentDate' : IDL.Text,
    'patientName' : IDL.Text,
    'doctorName' : IDL.Text,
    'department' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const LoginResponse = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'sessionToken' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AppointmentPartial, 'err' : IDL.Text })],
        [],
      ),
    'completeConsultation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'confirmPayment' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'getAllConsultations' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(PatientRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyAppointments' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Appointment), 'err' : IDL.Text })],
        ['query'],
      ),
    'getPatientRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(PatientRecord), 'err' : IDL.Text })],
        ['query'],
      ),
    'getQueue' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(Appointment), 'err' : IDL.Text })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : LoginResponse, 'err' : IDL.Text })],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'resetAppointments' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'userId' : IDL.Text,
              'name' : IDL.Text,
              'role' : IDL.Text,
            })
          ),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };