/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : string,
  'paymentStatus' : string,
  'tokenNumber' : bigint,
  'patientId' : string,
  'createdAt' : bigint,
  'appointmentDate' : string,
  'patientName' : string,
  'doctorName' : string,
  'department' : string,
  'timeSlot' : string,
}
export interface AppointmentPartial { 'id' : string, 'tokenNumber' : bigint }
export interface DashboardStats {
  'appointmentCount' : bigint,
  'doctorCount' : bigint,
  'patientCount' : bigint,
}
export interface LoginResponse {
  'userId' : string,
  'name' : string,
  'role' : string,
  'sessionToken' : string,
}
export interface PatientRecord {
  'id' : string,
  'doctorNotes' : string,
  'prescription' : string,
  'patientId' : string,
  'visitDate' : string,
  'diagnosis' : string,
  'patientName' : string,
  'doctorName' : string,
  'department' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : AppointmentPartial } |
      { 'err' : string }
  >,
  'completeConsultation' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'confirmPayment' : ActorMethod<
    [string, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getAllConsultations' : ActorMethod<
    [string],
    { 'ok' : Array<PatientRecord> } |
      { 'err' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyAppointments' : ActorMethod<
    [string],
    { 'ok' : Array<Appointment> } |
      { 'err' : string }
  >,
  'getPatientRecords' : ActorMethod<
    [string],
    { 'ok' : Array<PatientRecord> } |
      { 'err' : string }
  >,
  'getQueue' : ActorMethod<
    [string, string],
    { 'ok' : Array<Appointment> } |
      { 'err' : string }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string, string],
    { 'ok' : LoginResponse } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'register' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'resetAppointments' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'validateSession' : ActorMethod<
    [string],
    [] | [{ 'userId' : string, 'name' : string, 'role' : string }]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];